Added Signin and Signout
cmpe165spring2019/ReactApp pull request #9
Opened 2019-02-17 18:10 UTC by ChristianCastr0

2019-02-17 22:18 UTC, nguyenhoa2896 requested changes

2019-02-17 22:18 UTC, nguyenhoa2896 commented on server/firebase/firebase.js
> +const provider = new firebase.auth.GoogleAuthProvider();
const provider should be inside class Firebase constructor
should change `const provider` to`this.googleProvider`

2019-02-17 22:18 UTC, nguyenhoa2896 commented on server/firebase/firebase.js
>      this.database = app.database();
should add `this.adth = app.auth()`;

2019-02-17 22:20 UTC, nguyenhoa2896 requested changes

2019-02-17 22:20 UTC, nguyenhoa2896 commented on server/firebase/firebase.js
> +
should have `import 'firebase/auth';`

2019-02-18 03:55 UTC, nguyenhoa2896 approved these changes

2019-02-18 04:05 UTC, ChristianCastr0 commented on server/firebase/firebase.js
> +
Fixed

2019-02-18 04:06 UTC, merged